# -*- coding: utf-8 -*-
"""Architectural / site accessories added in the 'continue after the GitHub agent' round.  Everything here is regenerated by post_model.py on every run
(element ids end with -Xnnnn) from PDF-derived data files (pipeline/data/*.json) and from parameters documented below.

 1  GRC cornices              A2600 typical facade details (A: roof 75x50, C: string course 50x20) + elevations A200-A203 (levels: first-floor slab edge, roof parapet, top-roof parapet)
 2  ramp fence 90 cm          A102/A2301 note 'FENCING HIGHT 90cm' + F.L. +2.30 labels (wall top +1.40 -> fence top +2.30) along the straight south wall of the vehicle ramp
 3  site lighting             A2301 LIGHT DETAILS: 23 wall lamps 20 W 'H -230' on the boundary walls, 10 post lights (pipeline/site_lights.py -> data/site_lights.json)
 4  parking canopies          A102 (dashed 'above' outlines + X) / A1900 (stalls) / A200+A202 (profile): steel arched ribs every bay line, centre pipe column with Y struts, membrane
"""
import os, json, math
from shapely.geometry import Polygon, box, Point
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, "data")

MATS = {
    "canopy_steel": {"name": "فولاذ مدهون رمادي داكن — أضلاع وأعمدة مظلات المواقف", "color": "#565c63", "code": "A200 / A202"},
    "lamp_body": {"name": "كشاف خارجي مقاوم للماء (ألمنيوم رمادي داكن)", "color": "#3c4148", "code": "A2301"},
    "lamp_glass": {"name": "زجاج/ناشر الكشاف", "color": "#f4e7a8", "code": "A2301"},
    "furn_wood": {"name": "أثاث — خشب متوسط (إخراجي)", "color": "#a8794d", "code": "stage"},
    "furn_wood_light": {"name": "أثاث — خشب فاتح (إخراجي)", "color": "#d6bb92", "code": "stage"},
    "furn_wood_dark": {"name": "أثاث — خشب داكن (إخراجي)", "color": "#5b4332", "code": "stage"},
    "furn_white": {"name": "أثاث — أبيض (إخراجي)", "color": "#f2efe8", "code": "stage"},
    "furn_fabric_gray": {"name": "أثاث — قماش رمادي (إخراجي)", "color": "#8b9097", "code": "stage"},
    "furn_fabric_beige": {"name": "أثاث — قماش بيج (إخراجي)", "color": "#cdbd9f", "code": "stage"},
    "furn_dark": {"name": "أثاث — أسود/معدن داكن (إخراجي)", "color": "#2f3338", "code": "stage"},
    "stair_rail": {"name": "درابزين وسلالم فولاذ مجلفن مدهون (Ø30/40/50 مم)", "color": "#9aa1a8", "metal": 0.5, "rough": 0.45, "code": "A605"},
    "site_stopper": {"name": "مصدّ عجلات خرساني 195×15×15 سم", "color": "#9ea3a8", "code": "A1900"},
    "site_access_blue": {"name": "علامة موقف ذوي الإعاقة — أرضية زرقاء", "color": "#1f5fb4", "code": "A1900"},
    "site_access_white": {"name": "علامة موقف ذوي الإعاقة — رمز أبيض", "color": "#f4f6f8", "code": "A1900"},
    "lift_steel": {"name": "فولاذ مقاوم للصدأ مصقول (جدران المقصورة وإطارات الأبواب)", "color": "#c3c7cc", "metal": 0.65, "rough": 0.35, "code": "A900"},
    "lift_door": {"name": "أبواب مصعد فولاذ مقاوم للصدأ", "color": "#a9afb6", "metal": 0.7, "rough": 0.3, "code": "A900"},
    "lift_floor": {"name": "أرضية المقصورة (جرانيت داكن)", "color": "#6f7378", "code": "A900"},
    "lift_light": {"name": "إنارة المقصورة (لوحة LED سقفية)", "color": "#fff3c4", "emissive": "#ffe9a0", "emissiveIntensity": 1.0, "code": "A900"},
    "lift_btn": {"name": "أزرار نداء المصعد ومؤشر الوصول", "color": "#ffb347", "emissive": "#ff9a2e", "emissiveIntensity": 1.1, "code": "A900"},
}

# ------------------------------------------------------------------------------------------------------------- helpers
def _e(c, l, g, t, m, mark=None, a=None, src=None, grp=None, stage=None):
    e = {"c": c, "l": l, "g": g, "mark": mark, "t": t, "m": m, "a": a or {}, "src": list(src or [])}
    if grp: e["grp"] = grp
    if stage: e["stage"] = stage
    return e

def _rings(pg):
    out = []
    for q in (list(pg.geoms) if hasattr(pg, "geoms") else [pg]):
        if q.is_empty or q.area < 20 or q.geom_type != "Polygon": continue
        out.append(([[round(x, 1), round(y, 1)] for x, y in list(q.exterior.coords)[:-1]], [[[round(x, 1), round(y, 1)] for x, y in list(h.coords)[:-1]] for h in q.interiors]))
    return out

def _band(poly, d0, d1, z0, z1):
    """prism geometries for the band between the outline offset by d0 and by d1 (cm, outward)"""
    outer = poly.buffer(d1, join_style=2); inner = poly.buffer(d0, join_style=2) if d0 > 0 else poly
    return [["p", o, round(z0, 3), round(z1, 3)] + ([h] if h else []) for o, h in _rings(outer.difference(inner))]

# ------------------------------------------------------------------------------------------------------------- 1 cornices
# profiles: (z_from_bottom, z_to, projection cm) — stepped approximation of the GRC ogee of A2600 details A / C
PROF_A = [(0.00, 0.04, 9), (0.04, 0.18, 14), (0.18, 0.37, 24), (0.37, 0.58, 36), (0.58, 0.66, 46), (0.66, 0.75, 50)]   # roof parapet: 75 high x 50 projecting (A2600 detail A: 4+33+21+9..7)
PROF_C = [(0.00, 0.03, 6), (0.03, 0.25, 12), (0.25, 0.36, 16), (0.36, 0.50, 20)]                                       # string course: 50 high x 20 projecting (A2600 detail C: 3+22+6.5+14)
SRC_CORN = ["ARCH2 ص58 (A2600 تفاصيل تثبيت GRC — A و C)", "ARCH1 ص10–13 (A200–A203 الواجهات: كورنيش GRC بند 2 «GRC EXTERNAL ACRYLIC PAINT (BEIGE COLOR)»)"]

def cornices(M):
    out = []; TOWER = box(84, -91, 3205, 1880)
    Tblocks = unary_union([box(95, 760, 675, 1040), box(655, 460, 2645, 800), box(1975, 800, 2645, 1340)])
    specs = [("1", "string", TOWER, 5.34, PROF_C, "كورنيش حزام الدور الأول (GRC)", "50 × 20 سم", "حافة بلاطة الدور الأول (القمة +5.84)"),
             ("R", "roof", TOWER, 25.25 - 0.75, PROF_A, "كورنيش سور السطح (GRC)", "75 × 50 سم", "قمة سور السطح +25.25"),
             ("T", "top", Tblocks, 27.25 - 0.50, PROF_C, "كورنيش سور سطح الغرف العلوية (GRC)", "50 × 20 سم", "قمة السور العلوي +27.25")]
    for lv, kind, poly, z0, prof, nm, size, where in specs:
        for i, (a, b, proj) in enumerate(prof):
            d0 = prof[i - 1][2] if i else 0
            for g in _band(poly, 0, proj, z0 + a, z0 + b) if True else []:
                out.append(_e("A.clad", lv, g, "grc_cornice_" + kind, "clad_grc", "GRC-" + kind.upper(),
                              {"kind": "كورنيش GRC", "size_cm": size, "where": where}, SRC_CORN, grp=f"cornice-{kind}"))
    return out

# ------------------------------------------------------------------------------------------------------------- 2 ramp fence
def ramp_fence():
    out = []; y = 3801.0; x0, x1 = 1850.0, 2920.0; z0, z1 = 1.40, 2.30
    src = ["ARCH2 ص50 (A2301): «FENCING HIGHT 90cm» + F.L. +2.30 — خط الجدار الاستنادي الجنوبي للمنحدر (Landscape Parepet y=3791–3811)",
           "قمة الجدار +1.40 (F.L. +1.40 على القوس) فتكون قمة السياج +2.30 = F.L. +2.30 المكتوب"]
    asm = {}
    for zr in (z0 + 0.06, 1.85, z1 - 0.02):
        out.append(_e("A.rail", "G", ["t", [[x0, y, round(zr, 3)], [x1, y, round(zr, 3)]], 4.0], "fence_ramp", "fence_steel", "FENCE-90", dict(asm, kind="سياج", height_cm=90), src, grp="rampfence"))
    n = int((x1 - x0) // 150) + 1
    for k in range(n + 1):
        xx = min(x1, x0 + k * (x1 - x0) / n)
        out.append(_e("A.rail", "G", ["cyl", round(xx, 1), y, 3.0, z0, z1], "fence_ramp", "fence_steel", "FENCE-90", {"kind": "عمود السياج"}, src, grp="rampfence"))
    k = 0; xx = x0 + 6
    while xx < x1:
        out.append(_e("A.rail", "G", ["cyl", round(xx, 1), y, 1.0, z0 + 0.06, z1 - 0.02], "fence_ramp", "fence_steel", "FENCE-90", {"kind": "قضيب عمودي"}, src, grp="rampfence"))
        xx += 12; k += 1
    return out

# ------------------------------------------------------------------------------------------------------------- 3 site lights
def _ground_z(M, x, y):
    best = 0.20
    for e in M["els"]:
        if e["c"] != "A.site" or e["l"] != "G" or e["t"] not in ("site_paving", "site_planter_bed", "site_sand_bed", "site_rubber", "site_asphalt", "site_grass") or e["g"][0] != "p": continue
        g = e["g"]
        try:
            if Polygon(g[1], g[4] if len(g) > 4 and g[4] else None).buffer(0).contains(Point(x, y)): best = max(best, g[3])
        except Exception: pass
    return best

def site_lights(M):
    p = os.path.join(D, "site_lights.json")
    if not os.path.exists(p): return []
    S = json.load(open(p, encoding="utf-8")); out = []
    src = [S["src"], "مفتاح «LIGHT DETAILS» على A2301: WATER PROOF OUTDOOR WALL MOUNTED LAMP (طبقة EL- Wall Mount WP 20W) / POST LIGHT"]
    FACE = {"W": (-60.1, 1, 0), "E": (4470.7, -1, 0), "N": (None, 0, -1)}
    for i, w in enumerate(S["wall"], 1):
        zc = 0.20 + 2.30                                             # 'H -230' above the +0.20 paving datum
        if w["side"] in ("W", "E"):
            fx = FACE[w["side"]][0]; sg = FACE[w["side"]][1]
            g = ["b", round(fx + sg * 9, 1), w["y"], 16, 18, 0, round(zc - 0.12, 3), round(zc + 0.12, 3)]
            g2 = ["b", round(fx + sg * 1.5, 1), w["y"], 3, 14, 0, round(zc - 0.10, 3), round(zc + 0.10, 3)]
        else:
            fy = 4470.0
            g = ["b", w["x"], round(fy - 9, 1), 18, 16, 0, round(zc - 0.12, 3), round(zc + 0.12, 3)]
            g2 = ["b", w["x"], round(fy - 1.5, 1), 14, 3, 0, round(zc - 0.10, 3), round(zc + 0.10, 3)]
        a = {"kind": "كشاف جداري", "power_w": 20, "mount_h_m": 2.30, "side": {"W": "السور الغربي", "E": "السور الشرقي", "N": "السور الشمالي"}.get(w["side"])}
        out.append(_e("E.light", "G", g, "site_wall_lamp", "lamp_body", f"WL-{i:02d}", a, src, grp=f"wl{i}"))
        out.append(_e("E.light", "G", g2, "site_wall_lamp", "lamp_glass", f"WL-{i:02d}", a, src, grp=f"wl{i}"))
    for i, q in enumerate(S["post"], 1):
        z0 = round(_ground_z(M, q["x"], q["y"]), 2); H = 3.50; x, y = q["x"], q["y"]
        a = {"kind": "عمود إنارة", "base_z_m": z0, "pole_h_m": H}
        grp = f"pl{i}"
        out.append(_e("E.light", "G", ["cyl", x, y, 22, z0, round(z0 + 0.18, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["cyl", x, y, 5.5, z0, round(z0 + H, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        for dx, dy in ((26, 26), (-26, 26), (26, -26), (-26, -26)):
            out.append(_e("E.light", "G", ["cyl", x + dx, y + dy, 8, round(z0 + H - 0.16, 3), round(z0 + H + 0.04, 3)], "site_post_light", "lamp_glass", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["b", x, y, 62, 4, 45, round(z0 + H - 0.10, 3), round(z0 + H - 0.05, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["b", x, y, 62, 4, -45, round(z0 + H - 0.10, 3), round(z0 + H - 0.05, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
    return out

# ------------------------------------------------------------------------------------------------------------- 4 parking canopies
# blocks: (name, drive-way edge x, far edge x, direction (+1: far side at larger x), y lines (bay boundaries), bay numbers)
BLOCKS = [("W1", 3329.0, 2761.0, -1, [1870, 2120, 2270, 2520, 2790, 3060, 3330], "10–14"),
          ("E1", 3904.0, 4472.0, +1, [1710, 1980, 2250, 2520, 2790, 3060, 3330], "04–09"),
          ("E2", 3904.0, 4472.0, +1, [220, 490, 760, 1030], "01–03")]
# profile read off the A200 elevation (u = distance from the drive-way side, cm; z above datum): left end, crown, wall end
PTS_U = [(4, 2.78), (277, 3.40), (567, 2.60)]
U_COL, Z_COL = 479.0, 2.70             # centre pipe column (x=4383 on E blocks): top +2.70
STRUT = [(479.0, 1.65, 321.0, 3.255), (479.0, 1.65, 562.0, 2.58)]   # Y struts: from the column at +1.65 to the arc

def _arc_z(u):
    (u0, z0), (u1, z1), (u2, z2) = PTS_U
    # Lagrange quadratic through the three read-off points
    return (z0 * (u - u1) * (u - u2) / ((u0 - u1) * (u0 - u2)) + z1 * (u - u0) * (u - u2) / ((u1 - u0) * (u1 - u2)) + z2 * (u - u0) * (u - u1) / ((u2 - u0) * (u2 - u1)))

def parking_canopies(M):
    out = []
    src = ["ARCH1 ص5 (A102): مستطيلات «A-HIDDEN ABOVE» بخطوط X فوق كتل المواقف (568 سم) وخطوط الحزم عند كل فاصل مواقف",
           "ARCH1 ص10 و12 (A200/A202): مقطع المظلة المقوّسة — قمة الحزمة T.O.B +3.00، عمود وسطي 250 سم وساقان مائلتان (145 سم)",
           "ARCH1 ص11 (A201): امتداد المظلة على طول المواقف؛ ARCH2 ص38 (A1900): أبعاد الموقف 270×550 سم"]
    base = 0.20
    for name, xdw, xfar, sg, ys, bays in BLOCKS:
        x_at = lambda u: xdw + sg * u
        n = 24; us = [4 + (567 - 4) * k / n for k in range(n + 1)]
        grp = f"canopy-{name}"
        a0 = {"block": name, "bays": bays, "ribs": len(ys), "span_cm": 568, "top_of_beam_m": 3.00}
        for k, y in enumerate(ys):
            out.append(_e("A.site", "G", ["t", [[round(x_at(u), 1), y, round(base + _arc_z(u) - 0.20 + 0.0, 3)] for u in us], 12.0], "canopy_rib", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
            xc = x_at(U_COL)
            out.append(_e("A.site", "G", ["cyl", round(xc, 1), y, 10, base, round(base + Z_COL - 0.20 + 0.0, 3)], "canopy_column", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
            for (ua, za, ub, zb) in STRUT:
                out.append(_e("A.site", "G", ["t", [[round(x_at(ua), 1), y, round(base + za - 0.20, 3)], [round(x_at(ub), 1), y, round(base + zb - 0.20, 3)]], 8.0], "canopy_strut", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
        ymid = (ys[0] + ys[-1]) / 2.0; width = ys[-1] - ys[0] + 12
        out.append(_e("A.site", "G", ["rs", [[round(x_at(u), 1), ymid, round(base + _arc_z(u) - 0.20 + 0.07, 3)] for u in us], width, 0.03], "canopy_membrane", "shade_fabric", f"CANOPY-{name}", a0, src, grp=grp))
    return out


# ------------------------------------------------------------------------------------------------------------- 5 lifts (cars with lights + landing doors)
LIFT_SRC = ["ARCH2 ص17 (A900 تفاصيل المصاعد): مصعدان متجاوران، فتحة إنشائية للباب ارتفاعها 230 سم، توقفات B وG و1–5 والسطح",
            "ARCH1 ص6–7 (A103/A104): موضع البئرين وجدرانهما؛ المقصورة 140×160 سم مقدَّرة من فتحة البئر (كما كانت في النموذج)"]
LIFT_CARS = [("L1", 1565.0, 1705.0, "G"), ("L2", 1785.0, 1925.0, "3")]
LIFT_STOPS = ["B", "G", "1", "2", "3", "4", "5", "R"]
YA, YB, YF = 1040.0, 1200.0, 1020.0          # car front / back, landing-door plane (front of the shaft)

def lifts(M):
    out = []; LV = {l["id"]: l for l in M["levels"]}
    stops = "B,G,1–5,R"
    for car, xa, xb, lv0 in LIFT_CARS:
        xc = (xa + xb) / 2.0; z0 = LV[lv0]["ffl"] + 0.05
        a = {"car": car, "stops": stops, "cab_cm": "140×160 (تقديري من فتحة البئر)", "door_clear_cm": 110, "cab_h_m": 2.20}
        def part(x0, y0, x1, y1, za, zb, mat, t="lift_car"):
            out.append(_e("A.fix", lv0, ["r", x0, y0, x1, y1, round(z0 + za, 3), round(z0 + zb, 3)], t, mat, "LIFT-" + car, a, LIFT_SRC, grp="lift-" + car))
        part(xa, YA, xb, YB, 0.00, 0.06, "lift_floor")
        part(xa, YA, xa + 4, YB, 0.06, 2.26, "lift_steel"); part(xb - 4, YA, xb, YB, 0.06, 2.26, "lift_steel"); part(xa + 4, YB - 4, xb - 4, YB, 0.06, 2.26, "lift_steel")
        part(xa + 4, YA, xc - 55, YA + 4, 0.06, 2.26, "lift_steel"); part(xc + 55, YA, xb - 4, YA + 4, 0.06, 2.26, "lift_steel"); part(xc - 55, YA, xc + 55, YA + 4, 2.10, 2.26, "lift_steel")
        part(xc - 55, YA, xc - 1, YA + 3, 0.06, 2.10, "lift_door"); part(xc + 1, YA, xc + 55, YA + 3, 0.06, 2.10, "lift_door")
        part(xa, YA, xb, YB, 2.26, 2.32, "lift_steel")
        part(xc - 45, (YA + YB) / 2 - 45, xc + 45, (YA + YB) / 2 + 45, 2.245, 2.26, "lift_light")
        part(xa + 8, YB - 8, xb - 8, YB - 4, 0.88, 0.93, "lift_steel")                 # back handrail
    ld_src = LIFT_SRC + ["ARCH2 ص17: باب هبوط ثنائي الضلفة مركزي الفتح من فولاذ مقاوم للصدأ؛ عرض الفتحة الصافي 110 سم"]
    for lv in LIFT_STOPS:
        L = LV[lv]; ffl = L["ffl"]; top = L["top"]
        for car, xa, xb, _ in LIFT_CARS:
            xc = (xa + xb) / 2.0
            ad = {"car": car, "level": lv, "clear_w_cm": 110, "clear_h_cm": 210}
            def el(c, t, x0, y0, x1, y1, za, zb, mat, mark, extra=None, grp=None):
                aa = dict(ad); aa.update(extra or {})
                out.append(_e(c, lv, ["r", x0, y0, x1, y1, round(za, 3), round(zb, 3)], t, mat, mark, aa, ld_src, grp=grp or f"landing-{car}-{lv}"))
            if top - (ffl + 2.30) > 0.05: el("A.wall", "lift_front_wall", xa, YF, xb, YF + 20, ffl + 2.30, top, "block_ext", "LIFT-FRONT-" + car)
            if xc - 60 - xa > 1:
                el("A.wall", "lift_front_wall", xa, YF, xc - 60, YF + 20, ffl, ffl + 2.30, "block_ext", "LIFT-FRONT-" + car); el("A.wall", "lift_front_wall", xc + 60, YF, xb, YF + 20, ffl, ffl + 2.30, "block_ext", "LIFT-FRONT-" + car)
            el("A.door", "lift_landing_door", xc - 60, YF + 2, xc + 60, YF + 14, ffl + 2.10, ffl + 2.30, "lift_steel", f"LD-{car}-{lv}")
            el("A.door", "lift_landing_door", xc - 60, YF + 2, xc - 55, YF + 14, ffl, ffl + 2.10, "lift_steel", f"LD-{car}-{lv}"); el("A.door", "lift_landing_door", xc + 55, YF + 2, xc + 60, YF + 14, ffl, ffl + 2.10, "lift_steel", f"LD-{car}-{lv}")
            el("A.door", "lift_landing_door", xc - 55, YF + 5, xc - 0.5, YF + 11, ffl + 0.02, ffl + 2.10, "lift_door", f"LD-{car}-{lv}"); el("A.door", "lift_landing_door", xc + 0.5, YF + 5, xc + 55, YF + 11, ffl + 0.02, ffl + 2.10, "lift_door", f"LD-{car}-{lv}")
            out.append(_e("A.fix", lv, ["r", xc - 10, YF - 4, xc + 10, YF + 2, round(ffl + 2.36, 3), round(ffl + 2.44, 3)], "lift_indicator", "lift_btn", f"LI-{car}-{lv}", dict(ad), ld_src, grp=f"landing-{car}-{lv}"))
        out.append(_e("A.fix", lv, ["r", 1739, 996, 1751, 1000, round(ffl + 1.00, 3), round(ffl + 1.22, 3)], "lift_call_panel", "lift_steel", f"LCP-{lv}", {"level": lv}, ld_src, grp=f"callpanel-{lv}"))
        out.append(_e("A.fix", lv, ["r", 1743, 995, 1747, 996, round(ffl + 1.08, 3), round(ffl + 1.12, 3)], "lift_call_panel", "lift_btn", f"LCP-{lv}", {"level": lv}, ld_src, grp=f"callpanel-{lv}"))
    return out


# ------------------------------------------------------------------------------------------------------------- 6 parking details (A1900) + curved shade sails (A2305)
PARK_BAYS = [  # (block, number, x_drive_side, x_rear, y0, y1, accessible)
    ("W1", "14", 3320.0, 2770.0, 1870.0, 2120.0, True), ("W1", "13", 3320.0, 2770.0, 2270.0, 2520.0, True), ("W1", "12", 3320.0, 2770.0, 2520.0, 2790.0, False),
    ("W1", "11", 3320.0, 2770.0, 2790.0, 3060.0, False), ("W1", "10", 3320.0, 2770.0, 3060.0, 3330.0, False)] + \
    [("E1", f"{n:02d}", 3920.0, 4471.0, 1710.0 + 270.0 * k, 1980.0 + 270.0 * k, False) for k, n in enumerate(range(4, 10))] + \
    [("E2", f"{n:02d}", 3920.0, 4471.0, 220.0 + 270.0 * k, 490.0 + 270.0 * k, False) for k, n in enumerate(range(1, 4))]

def parking_details():
    out = []
    src = ["ARCH2 ص38 (A1900): موقف نمطي 270×550 سم، مصدّ عجلات خرساني 195×15×15 سم، موقف ذوي الإعاقة بممر هاشور 150 سم وعلامة طلاء",
           "ARCH1 ص5 (A102) / ARCH2 ص50 (A2301): ترقيم المواقف 01–14 وكتل المواقف"]
    for blk, num, xd, xr, y0, y1, acc in PARK_BAYS:
        sg = -1 if xr < xd else 1; yc = (y0 + y1) / 2.0; xs = xr - sg * 47.5
        a = {"bay": num, "block": blk, "accessible": "نعم" if acc else "لا", "size_cm": f"{round(y1 - y0)} × {round(abs(xr - xd))}"}
        out.append(_e("A.site", "G", ["b", round(xs, 1), round(yc, 1), 15, 195, 0, 0.20, 0.35], "park_stopper", "site_stopper", f"STOPPER-{num}", a, src, grp=f"bay-{num}"))
        if acc:
            xm = xd + sg * (-1) * 0 + (-1 if xr < xd else 1) * 270
            out.append(_e("A.site", "G", ["b", round(xm, 1), round(yc, 1), 110, 110, 0, 0.20, 0.205], "park_access_sign", "site_access_blue", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
            hx, hy = xm - 18, yc + 28                                                      # white pictogram: head, body, seat, leg, wheel ring
            out.append(_e("A.site", "G", ["cyl", round(hx, 1), round(hy, 1), 7, 0.205, 0.21], "park_access_sign", "site_access_white", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
            out.append(_e("A.site", "G", ["b", round(hx, 1), round(hy - 22, 1), 9, 30, 0, 0.205, 0.21], "park_access_sign", "site_access_white", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
            out.append(_e("A.site", "G", ["b", round(hx + 14, 1), round(hy - 40, 1), 34, 9, 0, 0.205, 0.21], "park_access_sign", "site_access_white", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
            out.append(_e("A.site", "G", ["b", round(hx + 29, 1), round(hy - 52, 1), 9, 30, 0, 0.205, 0.21], "park_access_sign", "site_access_white", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
            ring = []
            for k in range(24):
                an = 2 * math.pi * k / 24; ring.append([round(hx + 6 + 26 * math.cos(an), 1), round(hy - 42 + 26 * math.sin(an), 1)])
            hole = [[round(hx + 6 + 20 * math.cos(2 * math.pi * k / 24), 1), round(hy - 42 + 20 * math.sin(2 * math.pi * k / 24), 1)] for k in range(24)]
            out.append(_e("A.site", "G", ["p", ring, 0.205, 0.21, hole], "park_access_sign", "site_access_white", f"ACCESS-{num}", a, src, grp=f"bay-{num}"))
    return out

SHED_TOP = [(1265, 2975), (1665, 2975), (2065, 2975)]; SHED_BOT = [(1065, 2355), (1465, 2355), (1865, 2355), (2265, 2355)]; ZT, ZB = 4.50, 3.50
def curved_sails():
    """5 tensile sails of the kids-area shed (A2305).  The plan draws every edge as a concave arc, so the flat triangles of landscape_els are replaced by
    sails whose edges bow inward (sag 7 % of the edge) and whose centre dips 0.20 m; filled as a fan of triangles."""
    P = lambda xy, z: (xy[0], xy[1], z)
    tris = [(P(SHED_TOP[0], ZT), P(SHED_BOT[0], ZB), P(SHED_BOT[1], ZB)), (P(SHED_TOP[1], ZT), P(SHED_BOT[1], ZB), P(SHED_BOT[2], ZB)), (P(SHED_TOP[2], ZT), P(SHED_BOT[2], ZB), P(SHED_BOT[3], ZB)),
            (P(SHED_TOP[0], ZT), P(SHED_TOP[1], ZT), P(SHED_BOT[1], ZB)), (P(SHED_TOP[1], ZT), P(SHED_TOP[2], ZT), P(SHED_BOT[2], ZB))]
    out = []; n = 6
    for i, (A, B, C) in enumerate(tris, 1):
        cen = ((A[0] + B[0] + C[0]) / 3, (A[1] + B[1] + C[1]) / 3, (A[2] + B[2] + C[2]) / 3 - 0.20)
        bnd = []
        for (p, q) in ((A, B), (B, C), (C, A)):
            L = math.hypot(q[0] - p[0], q[1] - p[1]); ux, uy = (cen[0] - (p[0] + q[0]) / 2), (cen[1] - (p[1] + q[1]) / 2); ul = math.hypot(ux, uy) or 1; ux, uy = ux / ul, uy / ul
            for k in range(n):
                t = k / n; sag = 0.07 * L * 4 * t * (1 - t)
                bnd.append((p[0] + (q[0] - p[0]) * t + ux * sag, p[1] + (q[1] - p[1]) * t + uy * sag, p[2] + (q[2] - p[2]) * t - 0.08 * 4 * t * (1 - t)))
        for k in range(len(bnd)):
            a_, b_ = bnd[k], bnd[(k + 1) % len(bnd)]
            out.append(_e("A.site", "G", ["tri", [[round(a_[0], 1), round(a_[1], 1), round(a_[2], 3)], [round(b_[0], 1), round(b_[1], 1), round(b_[2], 3)], [round(cen[0], 1), round(cen[1], 1), round(cen[2], 3)]], 1.2],
                          "shed_sail", "shade_fabric", f"SAIL-{i}", {"kind": "شراع ظل", "note": "قماش PVC مثقّب — حواف مقوّسة للداخل (7% من طول الحافة) كما في مسقط A2305؛ تقعّر الوسط 20 سم تقدير"},
                          ["ARCH2 ص54 (A2305 ظلّة الألعاب): 7 أعمدة ⌀200 مم، قمم +4.50 (الصف الشمالي) و+3.50"], grp="shed"))
    return out


# ------------------------------------------------------------------------------------------------------------- 7 staged furniture (pipeline/furnish.py -> data/furniture.json)
FURN_TYPE = {"سرير": "furn_bed", "طاولة جانبية": "furn_nightstand", "دولاب": "furn_wardrobe", "كنبة": "furn_sofa", "طاولة قهوة": "furn_coffee_table", "وحدة تلفاز": "furn_tv_unit",
             "طاولة طعام مع 6 كراسٍ": "furn_dining", "غسالة": "furn_washer"}
FURN_LEVELS = {"typ": ("2", "3", "4", "5"), "1": ("1",)}

def furniture(M):
    p = os.path.join(D, "furniture.json")
    if not os.path.exists(p): return []
    F = json.load(open(p, encoding="utf-8")); LV = {l["id"]: l for l in M["levels"]}; out = []
    src = ["ترتيب إخراجي آلي (pipeline/furnish.py) — المخططات المعمارية A103/A104 لا ترسم أثاثًا منفصلًا؛ المواضع والأبعاد افتراضات للعرض فقط"]
    for key, flats in F.items():
        for lv in FURN_LEVELS[key]:
            ffl = LV[lv]["ffl"]
            for flat, items in flats.items():
                for k, it in enumerate(items):
                    t = FURN_TYPE.get(it["name"], "furn_other"); grp = f"furn-{lv}-{flat}-{k}"
                    for (ox, oy, w, d, z0, z1, mat) in it["parts"]:
                        if it.get("free"):
                            ang = math.radians(it["ang"]); c, s_ = math.cos(ang), math.sin(ang)
                            cx = it["c"][0] + ox * c - oy * s_; cy = it["c"][1] + ox * s_ + oy * c; rot = it["ang"]
                        else:
                            tt, nn = it["t"], it["n"]
                            cx = it["base"][0] + tt[0] * ox + nn[0] * oy; cy = it["base"][1] + tt[1] * ox + nn[1] * oy; rot = it["ang"]
                        e = _e("A.stage", lv, ["b", round(cx, 1), round(cy, 1), round(w, 1), round(d, 1), round(rot, 2), round(ffl + z0, 3), round(ffl + z1, 3)], t, mat, it["name"],
                               {"kind": "أثاث إخراجي", "room": it.get("room"), "size_cm": f"{round(it['w'])} × {round(it['d'])}"}, src, grp=grp, stage="furniture")
                        e["u"] = f"{lv}-{flat}"
                        out.append(e)
    return out


def zebra():
    """pedestrian crossing at the entrance of the drive way: 5 white stripes 60 x 175 cm, pitch 120 (A2301 layer 'A-Road Marks', also A401 'FRONT PLAN')"""
    out = []
    for k, x0 in enumerate((3350, 3470, 3590, 3710, 3830), 1):
        out.append(_e("A.site", "G", ["p", [[x0, 45], [x0 + 60, 45], [x0 + 60, 220], [x0, 220]], 0.10, 0.11], "site_mark", "site_mark", f"ZEBRA-{k}",
                      {"kind": "علامة مرور — عبور مشاة", "size_cm": "60 × 175"}, ["ARCH2 ص50 (A2301، طبقة A-Road Marks)", "ARCH1 ص17 (A401 FRONT PLAN)"], grp="zebra"))
    return out


# ------------------------------------------------------------------------------------------------------------- 8 stair balustrades + wall handrails (A605)
def stair_rails(M):
    """A605: wall handrail Ø40 at 0.95 m above the nosing line; open (well) side: guard with Ø50 posts @90, Ø30 balusters (clear 8 cm), rails at +0.20 / +0.95 / +1.20 above the nosing line"""
    out = []; flights = {}
    for e in M["els"]:
        if e["c"] == "S.stair" and e["t"] == "stair_step" and e["g"][0] == "r" and (e.get("grp") or "").startswith("STAIR"):
            flights.setdefault((e["grp"], e["a"]["flight"]), []).append(e)
    src = ["ARCH2 ص6 (A605 تفاصيل الدرابزين): درابزين الدرج، رباعي الأجزاء 20/75/25 سم، عمود Ø50 مم كل 90 سم، قضبان Ø30 مم بفراغ 8 سم، درابزين جداري Ø40 مم عند 0.95 م"]
    asm = {}
    for (grp, fl), steps in sorted(flights.items()):
        steps.sort(key=lambda e: e["a"]["step"]); lv = steps[0]["l"]
        pts = []                                                       # nosing line: (x_leading_edge, y0, y1, z_top)
        for e in steps:
            g = e["g"]; lead_x = g[1] if fl == "B" else g[1]
            pts.append((g[1], g[3], g[2], g[4], g[6]))
        y0 = min(p[2] for p in pts); y1 = max(p[3] for p in pts)
        # flight A runs west->east (y lower half), flight B east->west (y upper half)
        outer_y = (y0 + 4) if fl == "A" else (y1 - 4)
        inner_y = (y1 - 3) if fl == "A" else (y0 + 3)
        # nosing points ordered along the walking direction
        line = [((p[0] if fl == "A" else p[0]), p[4]) for p in pts]
        if fl == "A": line.append((pts[-1][1], pts[-1][4]))
        else: line.append((pts[-1][0] - 0.0, pts[-1][4]))
        def rail(y, h, dia, mat="stair_rail", tag="RAIL"):
            return _e("A.rail", lv, ["t", [[round(x, 1), round(y, 1), round(z + h, 3)] for x, z in line], dia], "stair_guard", mat, f"{grp}-{fl}-{tag}", dict(asm, flight=fl), src, grp=f"rail-{grp}-{fl}")
        out.append(rail(outer_y, 0.95, 4.0, tag="WALL"))
        for h, dia in ((0.20, 3.0), (0.95, 4.0), (1.20, 5.0)): out.append(rail(inner_y, h, dia, tag=f"G{round(h*100)}"))
        # posts every third tread + balusters every 11 cm along the sloping guard
        for k in range(0, len(pts), 3):
            x, z = line[k]
            out.append(_e("A.rail", lv, ["cyl", round(x, 1), round(inner_y, 1), 2.5, round(z, 3), round(z + 1.20, 3)], "stair_guard", "stair_rail", f"{grp}-{fl}-POST", dict(asm, flight=fl), src, grp=f"rail-{grp}-{fl}"))
        x_a, z_a = line[0]; x_b, z_b = line[-1]; Lx = abs(x_b - x_a); n = max(2, int(Lx // 11))
        for i in range(1, n):
            t = i / n; x = x_a + (x_b - x_a) * t; z = z_a + (z_b - z_a) * t
            out.append(_e("A.rail", lv, ["b", round(x, 1), round(inner_y, 1), 3, 3, 0, round(z + 0.20, 3), round(z + 1.20, 3)], "stair_guard", "stair_rail", f"{grp}-{fl}-BAL", dict(asm, flight=fl), src, grp=f"rail-{grp}-{fl}"))
    return out

# ------------------------------------------------------------------------------------------------------------- types
def types():
    def T(n, cf, sp, asm=None, sr=None):
        d = {"n": n, "cf": cf, "sp": sp}
        if asm: d["asm"] = asm
        if sr: d["sr"] = sr
        return d
    return {
        "grc_cornice_string": T("كورنيش حزام الدور الأول — GRC", "doc", [["المقطع (ارتفاع × بروز)", "50 × 20 سم"], ["المادة", "GRC بدهان أكريليك خارجي بيج (بند 2)"], ["الموضع", "حافة بلاطة الدور الأول حول المبنى (+5.34 إلى +5.84)"]],
                               ["المقطع المنحني (ogee) مقرَّب بأربع درجات؛ الأبعاد الكلية 50×20 سم من A2600"], ["A2600 تفصيل C", "A200–A203"]),
        "grc_cornice_roof": T("كورنيش سور السطح — GRC", "doc", [["المقطع (ارتفاع × بروز)", "75 × 50 سم (4+33+21+9..7)"], ["المادة", "GRC بدهان أكريليك خارجي بيج (بند 2)"], ["الموضع", "قمة سور السطح +25.25 حول المبنى"]],
                              ["المقطع المنحني (ogee) مقرَّب بست درجات؛ الأبعاد الكلية 75×50 سم من A2600"], ["A2600 تفصيل A", "A200–A203"]),
        "grc_cornice_top": T("كورنيش سور سطح الغرف العلوية — GRC", "derived", [["المقطع", "50 × 20 سم (نفس تفصيل C)"], ["الموضع", "قمة السور العلوي +27.25"]],
                             ["استُعمل تفصيل C لأن الواجهات تُظهر كورنيشًا أصغر من كورنيش السطح الرئيسي؛ التفصيل الدقيق غير مذكور"], ["A2600", "A200–A203"]),
        "fence_ramp": T("سياج المنحدر 90 سم", "doc", [["الارتفاع", "90 سم فوق قمة الجدار (+1.40 إلى +2.30)"], ["المادة", "فولاذ مدهون رمادي داكن (كسياج الألعاب)"], ["الموضع", "الجدار الجنوبي المستقيم للمنحدر x=1850..2920"]],
                            ["تقسيم القضبان العمودية (كل 12 سم) وأقطار الأنابيب وعدد الأعمدة افتراض", "السياج يبدأ من نهاية القوس x=2920 حتى x=1850 كما يوحي خط الإشارة في A2301"], ["A2301 «FENCING HIGHT 90cm»"]),
        "site_wall_lamp": T("كشاف جداري خارجي مقاوم للماء 20 واط", "doc", [["القدرة", "20 واط"], ["التركيب", "على السور، ارتفاع 2.30 م (H -230)"], ["الحماية", "مقاوم للماء (WP)"]],
                            ["منسوب +0.20 مرجع الأرض لقياس الارتفاع 2.30 م", "أبعاد الجسم (≈16×18×24 سم) من رمز المخطط"], ["A2301 LIGHT DETAILS"]),
        "site_post_light": T("عمود إنارة حديقة (POST LIGHT)", "derived", [["الرمز", "4 دوائر حول مركز على A2301"], ["الموضع", "الحدائق وممرات منطقة الألعاب"]],
                             ["ارتفاع العمود 3.5 م وشكل الرؤوس الأربعة والقدرة غير مذكورة — المخطط يعطي المسقط فقط (4 دوائر حول مركز)"], ["A2301 LIGHT DETAILS"]),
        "canopy_rib": T("ضلع قوس مظلة المواقف (فولاذ)", "doc", [["الارتفاع الأعلى للحزمة", "T.O.B +3.00"], ["العدد", "ضلع عند كل فاصل مواقف (270 سم)"], ["المقطع", "قوس منحنٍ بفتحة 568 سم"]],
                        ["منحنى القوس وارتفاع قمته (+3.40) وقطر الأنبوب ⌀12 سم قراءات من الرسم لا أرقام مكتوبة", "الصور (7 أغسطس) تؤكد مظلة غشائية بيج على هيكل فولاذي بينما A1700/A201 يذكران برجولة ألمنيوم بتأثير خشب — بانتظار تأكيدك أيّهما المعتمد"], ["A200/A202 المقطع", "A102 المسقط"]),
        "canopy_column": T("عمود مظلة المواقف (أنبوب فولاذ)", "doc", [["الارتفاع", "250 سم"], ["العدد", "عمود عند كل ضلع"]], ["القطر ⌀20 سم تقدير من الرسم", "موضع العمود على القوس (x≈4383 على الكتل الشرقية) مقروء من المقطع"], ["A200/A202"]),
        "canopy_strut": T("ساق مائلة لمظلة المواقف", "doc", [["الربط", "من العمود عند 145 سم إلى القوس"]], ["القطر ⌀8 سم تقدير"], ["A200/A202"]),
        "furn_bed": T("سرير (أثاث إخراجي)", "assumed", [["النوع", "كمالية إخراجية — للعرض لا للتنفيذ"], ["الأبعاد", "180–200 × 200 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي آلي حسب الغرفة والأبواب"], []),
        "furn_nightstand": T("طاولة جانبية (أثاث إخراجي)", "assumed", [["الأبعاد", "45 × 40 × 50 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "furn_wardrobe": T("دولاب (أثاث إخراجي)", "assumed", [["العمق", "60 سم"], ["الارتفاع", "2.30 م"]], ["غير مرسوم في هذا الموضع؛ A1300–A1302 تفاصيل دواليب غير مربوطة بالمساقط في هذا النموذج"], ["A1300–A1302"]),
        "furn_sofa": T("كنبة (أثاث إخراجي)", "assumed", [["الأبعاد", "230 × 95 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "furn_coffee_table": T("طاولة قهوة (أثاث إخراجي)", "assumed", [["الأبعاد", "110 × 60 × 40 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "furn_tv_unit": T("وحدة تلفاز (أثاث إخراجي)", "assumed", [["الأبعاد", "190 × 42 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "furn_dining": T("طاولة طعام مع 6 كراسٍ (أثاث إخراجي)", "assumed", [["الأبعاد", "190 × 95 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "furn_washer": T("غسالة (أثاث إخراجي)", "assumed", [["الأبعاد", "60 × 60 × 85 سم"]], ["غير مرسوم في المخططات؛ ترتيب افتراضي"], []),
        "stair_guard": T("درابزين الدرج (فولاذ)", "doc", [["الدرابزين الجداري", "Ø40 مم عند 0.95 م فوق خط حواف الدرجات"], ["جهة فتحة البئر", "حاجز: أعمدة Ø50 مم كل ~90 سم، قضبان Ø30 مم فراغ 8 سم، قضبان أفقية عند +0.20 و+0.95 و+1.20 م"], ["المادة", "فولاذ مجلفن مدهون"]], ["حساب مواضع الأعمدة والقضبان على الدرجات العشر تقريبي؛ لا يظهر مقطع الجناح العلوي عند الأرضيات"], ["A605"]),
        "park_stopper": T("مصدّ عجلات خرساني", "doc", [["الأبعاد", "195 × 15 × 15 سم"], ["الموضع", "40 سم من نهاية الموقف (A1900)"], ["المادة", "خرسانة"]], ["الارتفاع 15 سم من التفصيل؛ موضع المصدّ بالنسبة للمحور تقدير"], ["A1900 تفصيل 4"]),
        "park_access_sign": T("علامة موقف ذوي الإعاقة (طلاء)", "derived", [["النوع", "رمز كرسي متحرك أبيض على أرضية زرقاء"], ["المواقف", "13 و14"], ["الممر", "هاشور 150 سم بين الموقفين"]], ["أبعاد الرمز المرسوم ~110 سم وشكله المبسّط تقدير؛ A1900 يعطي رمز 201.7 سم"], ["A1900", "A2301"]),
        "lift_car": T("مقصورة مصعد (مع إنارة وأبواب)", "derived", [["الأبعاد", "140 × 160 سم (تقديرية من فتحة البئر)"], ["ارتفاع المقصورة الداخلي", "2.20 م"], ["فتحة الباب الصافية", "110 سم — ضلفتان مركزيتا الفتح"], ["التوقفات", "B وG و1–5 والسطح"], ["الإنارة", "لوحة LED سقفية"]],
                       ["أبعاد المقصورة وسُمك الجدران 4 سم وارتفاعها وتفاصيل الإنارة افتراض؛ A900 يعطي الفتحة الإنشائية 230 سم والتوقفات فقط", "السعة والسرعة والشركة المصنّعة غير مذكورة في المستندات"], ["A900", "A103/A104"]),
        "lift_landing_door": T("باب هبوط مصعد (فولاذ مقاوم للصدأ)", "derived", [["الفتحة الصافية", "110 × 210 سم"], ["النوع", "ضلفتان مركزيتا الفتح"], ["الفتحة الإنشائية", "230 سم (A900)"]],
                              ["عرض الفتحة 110 سم وسُمك الضلفة افتراض (A900 يعطي الارتفاع الإنشائي 230 فقط)"], ["A900"]),
        "lift_front_wall": T("جدار واجهة بئر المصعد (بلوك)", "derived", [["السماكة", "20 سم"], ["الارتفاع", "فوق وحول فتحة الباب حتى سقف الطابق"]], ["السماكة افتراض"], ["A900", "A103/A104"]),
        "lift_indicator": T("مؤشر وصول المصعد (Hall lantern)", "assumed", [["الموضع", "فوق باب الهبوط"]], ["الوجود والموضع افتراض هندسي — غير مرسوم في المستندات"], []),
        "lift_call_panel": T("لوحة نداء المصعد", "assumed", [["الارتفاع", "1.0–1.22 م"]], ["الوجود والموضع افتراض هندسي — غير مرسوم في المستندات"], []),
        "canopy_membrane": T("قماش مظلة المواقف (غشاء)", "derived", [["اللون", "بيج (من صور الموقع 7 أغسطس)"], ["الشكل", "سطح أسطواني فوق الأضلاع"]],
                             ["المادة وسُمك الغشاء غير محددين في المخططات؛ الصور تُظهر مظلة غشائية بيج بينما A1700/A201 يذكران برجولة ألمنيوم بتأثير خشب — بانتظار تأكيدك أيّهما المعتمد"], ["صور الموقع", "A102"]),
    }

def build(M):
    import arch_windows as AW
    W = AW.build(M)
    els = cornices(M) + ramp_fence() + site_lights(M) + parking_canopies(M) + lifts(M) + parking_details() + curved_sails() + furniture(M) + zebra() + stair_rails(M) + W["els"]
    mats = dict(MATS); mats.update(W["mats"])
    tp = types(); tp.update(AW.types(M))
    return {"els": els, "mats": mats, "types": tp}
