# -*- coding: utf-8 -*-
"""Architectural / site accessories added in the 'continue after the GitHub agent' round.  Everything here is regenerated by post_model.py on every run
(element ids end with -Xnnnn) from PDF-derived data files (pipeline/data/*.json) and from parameters documented below.

 1  GRC cornices              A2600 typical facade details (A: roof 75x50, C: string course 50x20) + elevations A200-A203 (levels: first-floor slab edge, roof parapet, top-roof parapet)
 2  ramp fence 90 cm          A102/A2301 note 'FENCING HIGHT 90cm' + F.L. +2.30 labels (wall top +1.40 -> fence top +2.30) along the straight south wall of the vehicle ramp
 3  site lighting             A2301 LIGHT DETAILS: 23 wall lamps 20 W 'H -230' on the boundary walls, 10 post lights (pipeline/site_lights.py -> data/site_lights.json)
 4  parking canopies          A102 (dashed 'above' outlines + X) / A1900 (stalls) / A200+A202 (profile): steel arched ribs every bay line, centre pipe column with Y struts, membrane
"""
import os, json, math
from shapely.geometry import Polygon, box, Point
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, "data")

MATS = {
    "canopy_steel": {"name": "فولاذ مدهون رمادي داكن — أضلاع وأعمدة مظلات المواقف", "color": "#565c63", "code": "A200 / A202"},
    "lamp_body": {"name": "كشاف خارجي مقاوم للماء (ألمنيوم رمادي داكن)", "color": "#3c4148", "code": "A2301"},
    "lamp_glass": {"name": "زجاج/ناشر الكشاف", "color": "#f4e7a8", "code": "A2301"},
}

# ------------------------------------------------------------------------------------------------------------- helpers
def _e(c, l, g, t, m, mark=None, a=None, src=None, grp=None, stage=None):
    e = {"c": c, "l": l, "g": g, "mark": mark, "t": t, "m": m, "a": a or {}, "src": list(src or [])}
    if grp: e["grp"] = grp
    if stage: e["stage"] = stage
    return e

def _rings(pg):
    out = []
    for q in (list(pg.geoms) if hasattr(pg, "geoms") else [pg]):
        if q.is_empty or q.area < 20 or q.geom_type != "Polygon": continue
        out.append(([[round(x, 1), round(y, 1)] for x, y in list(q.exterior.coords)[:-1]], [[[round(x, 1), round(y, 1)] for x, y in list(h.coords)[:-1]] for h in q.interiors]))
    return out

def _band(poly, d0, d1, z0, z1):
    """prism geometries for the band between the outline offset by d0 and by d1 (cm, outward)"""
    outer = poly.buffer(d1, join_style=2); inner = poly.buffer(d0, join_style=2) if d0 > 0 else poly
    return [["p", o, round(z0, 3), round(z1, 3)] + ([h] if h else []) for o, h in _rings(outer.difference(inner))]

# ------------------------------------------------------------------------------------------------------------- 1 cornices
# profiles: (z_from_bottom, z_to, projection cm) — stepped approximation of the GRC ogee of A2600 details A / C
PROF_A = [(0.00, 0.04, 9), (0.04, 0.18, 14), (0.18, 0.37, 24), (0.37, 0.58, 36), (0.58, 0.66, 46), (0.66, 0.75, 50)]   # roof parapet: 75 high x 50 projecting (A2600 detail A: 4+33+21+9..7)
PROF_C = [(0.00, 0.03, 6), (0.03, 0.25, 12), (0.25, 0.36, 16), (0.36, 0.50, 20)]                                       # string course: 50 high x 20 projecting (A2600 detail C: 3+22+6.5+14)
SRC_CORN = ["ARCH2 ص58 (A2600 تفاصيل تثبيت GRC — A و C)", "ARCH1 ص10–13 (A200–A203 الواجهات: كورنيش GRC بند 2 «GRC EXTERNAL ACRYLIC PAINT (BEIGE COLOR)»)"]

def cornices(M):
    out = []; TOWER = box(84, -91, 3205, 1880)
    Tblocks = unary_union([box(95, 760, 675, 1040), box(655, 460, 2645, 800), box(1975, 800, 2645, 1340)])
    specs = [("1", "string", TOWER, 5.34, PROF_C, "كورنيش حزام الدور الأول (GRC)", "50 × 20 سم", "حافة بلاطة الدور الأول (القمة +5.84)"),
             ("R", "roof", TOWER, 25.25 - 0.75, PROF_A, "كورنيش سور السطح (GRC)", "75 × 50 سم", "قمة سور السطح +25.25"),
             ("T", "top", Tblocks, 27.25 - 0.50, PROF_C, "كورنيش سور سطح الغرف العلوية (GRC)", "50 × 20 سم", "قمة السور العلوي +27.25")]
    for lv, kind, poly, z0, prof, nm, size, where in specs:
        for i, (a, b, proj) in enumerate(prof):
            d0 = prof[i - 1][2] if i else 0
            for g in _band(poly, 0, proj, z0 + a, z0 + b) if True else []:
                out.append(_e("A.clad", lv, g, "grc_cornice_" + kind, "clad_grc", "GRC-" + kind.upper(),
                              {"kind": "كورنيش GRC", "size_cm": size, "where": where}, SRC_CORN, grp=f"cornice-{kind}"))
    return out

# ------------------------------------------------------------------------------------------------------------- 2 ramp fence
def ramp_fence():
    out = []; y = 3801.0; x0, x1 = 1850.0, 2920.0; z0, z1 = 1.40, 2.30
    src = ["ARCH2 ص50 (A2301): «FENCING HIGHT 90cm» + F.L. +2.30 — خط الجدار الاستنادي الجنوبي للمنحدر (Landscape Parepet y=3791–3811)",
           "قمة الجدار +1.40 (F.L. +1.40 على القوس) فتكون قمة السياج +2.30 = F.L. +2.30 المكتوب"]
    asm = {}
    for zr in (z0 + 0.06, 1.85, z1 - 0.02):
        out.append(_e("A.rail", "G", ["t", [[x0, y, round(zr, 3)], [x1, y, round(zr, 3)]], 4.0], "fence_ramp", "fence_steel", "FENCE-90", dict(asm, kind="سياج", height_cm=90), src, grp="rampfence"))
    n = int((x1 - x0) // 150) + 1
    for k in range(n + 1):
        xx = min(x1, x0 + k * (x1 - x0) / n)
        out.append(_e("A.rail", "G", ["cyl", round(xx, 1), y, 3.0, z0, z1], "fence_ramp", "fence_steel", "FENCE-90", {"kind": "عمود السياج"}, src, grp="rampfence"))
    k = 0; xx = x0 + 6
    while xx < x1:
        out.append(_e("A.rail", "G", ["cyl", round(xx, 1), y, 1.0, z0 + 0.06, z1 - 0.02], "fence_ramp", "fence_steel", "FENCE-90", {"kind": "قضيب عمودي"}, src, grp="rampfence"))
        xx += 12; k += 1
    return out

# ------------------------------------------------------------------------------------------------------------- 3 site lights
def _ground_z(M, x, y):
    best = 0.20
    for e in M["els"]:
        if e["c"] != "A.site" or e["l"] != "G" or e["t"] not in ("site_paving", "site_planter_bed", "site_sand_bed", "site_rubber", "site_asphalt", "site_grass") or e["g"][0] != "p": continue
        g = e["g"]
        try:
            if Polygon(g[1], g[4] if len(g) > 4 and g[4] else None).buffer(0).contains(Point(x, y)): best = max(best, g[3])
        except Exception: pass
    return best

def site_lights(M):
    p = os.path.join(D, "site_lights.json")
    if not os.path.exists(p): return []
    S = json.load(open(p, encoding="utf-8")); out = []
    src = [S["src"], "مفتاح «LIGHT DETAILS» على A2301: WATER PROOF OUTDOOR WALL MOUNTED LAMP (طبقة EL- Wall Mount WP 20W) / POST LIGHT"]
    FACE = {"W": (-60.1, 1, 0), "E": (4470.7, -1, 0), "N": (None, 0, -1)}
    for i, w in enumerate(S["wall"], 1):
        zc = 0.20 + 2.30                                             # 'H -230' above the +0.20 paving datum
        if w["side"] in ("W", "E"):
            fx = FACE[w["side"]][0]; sg = FACE[w["side"]][1]
            g = ["b", round(fx + sg * 9, 1), w["y"], 16, 18, 0, round(zc - 0.12, 3), round(zc + 0.12, 3)]
            g2 = ["b", round(fx + sg * 1.5, 1), w["y"], 3, 14, 0, round(zc - 0.10, 3), round(zc + 0.10, 3)]
        else:
            fy = 4470.0
            g = ["b", w["x"], round(fy - 9, 1), 18, 16, 0, round(zc - 0.12, 3), round(zc + 0.12, 3)]
            g2 = ["b", w["x"], round(fy - 1.5, 1), 14, 3, 0, round(zc - 0.10, 3), round(zc + 0.10, 3)]
        a = {"kind": "كشاف جداري", "power_w": 20, "mount_h_m": 2.30, "side": {"W": "السور الغربي", "E": "السور الشرقي", "N": "السور الشمالي"}.get(w["side"])}
        out.append(_e("E.light", "G", g, "site_wall_lamp", "lamp_body", f"WL-{i:02d}", a, src, grp=f"wl{i}"))
        out.append(_e("E.light", "G", g2, "site_wall_lamp", "lamp_glass", f"WL-{i:02d}", a, src, grp=f"wl{i}"))
    for i, q in enumerate(S["post"], 1):
        z0 = round(_ground_z(M, q["x"], q["y"]), 2); H = 3.50; x, y = q["x"], q["y"]
        a = {"kind": "عمود إنارة", "base_z_m": z0, "pole_h_m": H}
        grp = f"pl{i}"
        out.append(_e("E.light", "G", ["cyl", x, y, 22, z0, round(z0 + 0.18, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["cyl", x, y, 5.5, z0, round(z0 + H, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        for dx, dy in ((26, 26), (-26, 26), (26, -26), (-26, -26)):
            out.append(_e("E.light", "G", ["cyl", x + dx, y + dy, 8, round(z0 + H - 0.16, 3), round(z0 + H + 0.04, 3)], "site_post_light", "lamp_glass", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["b", x, y, 62, 4, 45, round(z0 + H - 0.10, 3), round(z0 + H - 0.05, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
        out.append(_e("E.light", "G", ["b", x, y, 62, 4, -45, round(z0 + H - 0.10, 3), round(z0 + H - 0.05, 3)], "site_post_light", "lamp_body", f"PL-{i:02d}", a, src, grp=grp))
    return out

# ------------------------------------------------------------------------------------------------------------- 4 parking canopies
# blocks: (name, drive-way edge x, far edge x, direction (+1: far side at larger x), y lines (bay boundaries), bay numbers)
BLOCKS = [("W1", 3329.0, 2761.0, -1, [1870, 2120, 2270, 2520, 2790, 3060, 3330], "10–14"),
          ("E1", 3904.0, 4472.0, +1, [1710, 1980, 2250, 2520, 2790, 3060, 3330], "04–09"),
          ("E2", 3904.0, 4472.0, +1, [220, 490, 760, 1030], "01–03")]
# profile read off the A200 elevation (u = distance from the drive-way side, cm; z above datum): left end, crown, wall end
PTS_U = [(4, 2.78), (277, 3.40), (567, 2.60)]
U_COL, Z_COL = 479.0, 2.70             # centre pipe column (x=4383 on E blocks): top +2.70
STRUT = [(479.0, 1.65, 321.0, 3.255), (479.0, 1.65, 562.0, 2.58)]   # Y struts: from the column at +1.65 to the arc

def _arc_z(u):
    (u0, z0), (u1, z1), (u2, z2) = PTS_U
    # Lagrange quadratic through the three read-off points
    return (z0 * (u - u1) * (u - u2) / ((u0 - u1) * (u0 - u2)) + z1 * (u - u0) * (u - u2) / ((u1 - u0) * (u1 - u2)) + z2 * (u - u0) * (u - u1) / ((u2 - u0) * (u2 - u1)))

def parking_canopies(M):
    out = []
    src = ["ARCH1 ص5 (A102): مستطيلات «A-HIDDEN ABOVE» بخطوط X فوق كتل المواقف (568 سم) وخطوط الحزم عند كل فاصل مواقف",
           "ARCH1 ص10 و12 (A200/A202): مقطع المظلة المقوّسة — قمة الحزمة T.O.B +3.00، عمود وسطي 250 سم وساقان مائلتان (145 سم)",
           "ARCH1 ص11 (A201): امتداد المظلة على طول المواقف؛ ARCH2 ص38 (A1900): أبعاد الموقف 270×550 سم"]
    base = 0.20
    for name, xdw, xfar, sg, ys, bays in BLOCKS:
        x_at = lambda u: xdw + sg * u
        n = 24; us = [4 + (567 - 4) * k / n for k in range(n + 1)]
        grp = f"canopy-{name}"
        a0 = {"block": name, "bays": bays, "ribs": len(ys), "span_cm": 568, "top_of_beam_m": 3.00}
        for k, y in enumerate(ys):
            out.append(_e("A.site", "G", ["t", [[round(x_at(u), 1), y, round(base + _arc_z(u) - 0.20 + 0.0, 3)] for u in us], 12.0], "canopy_rib", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
            xc = x_at(U_COL)
            out.append(_e("A.site", "G", ["cyl", round(xc, 1), y, 10, base, round(base + Z_COL - 0.20 + 0.0, 3)], "canopy_column", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
            for (ua, za, ub, zb) in STRUT:
                out.append(_e("A.site", "G", ["t", [[round(x_at(ua), 1), y, round(base + za - 0.20, 3)], [round(x_at(ub), 1), y, round(base + zb - 0.20, 3)]], 8.0], "canopy_strut", "canopy_steel", f"CANOPY-{name}", a0, src, grp=grp))
        ymid = (ys[0] + ys[-1]) / 2.0; width = ys[-1] - ys[0] + 12
        out.append(_e("A.site", "G", ["rs", [[round(x_at(u), 1), ymid, round(base + _arc_z(u) - 0.20 + 0.07, 3)] for u in us], width, 0.03], "canopy_membrane", "shade_fabric", f"CANOPY-{name}", a0, src, grp=grp))
    return out

# ------------------------------------------------------------------------------------------------------------- types
def types():
    def T(n, cf, sp, asm=None, sr=None):
        d = {"n": n, "cf": cf, "sp": sp}
        if asm: d["asm"] = asm
        if sr: d["sr"] = sr
        return d
    return {
        "grc_cornice_string": T("كورنيش حزام الدور الأول — GRC", "doc", [["المقطع (ارتفاع × بروز)", "50 × 20 سم"], ["المادة", "GRC بدهان أكريليك خارجي بيج (بند 2)"], ["الموضع", "حافة بلاطة الدور الأول حول المبنى (+5.34 إلى +5.84)"]],
                               ["المقطع المنحني (ogee) مقرَّب بأربع درجات؛ الأبعاد الكلية 50×20 سم من A2600"], ["A2600 تفصيل C", "A200–A203"]),
        "grc_cornice_roof": T("كورنيش سور السطح — GRC", "doc", [["المقطع (ارتفاع × بروز)", "75 × 50 سم (4+33+21+9..7)"], ["المادة", "GRC بدهان أكريليك خارجي بيج (بند 2)"], ["الموضع", "قمة سور السطح +25.25 حول المبنى"]],
                              ["المقطع المنحني (ogee) مقرَّب بست درجات؛ الأبعاد الكلية 75×50 سم من A2600"], ["A2600 تفصيل A", "A200–A203"]),
        "grc_cornice_top": T("كورنيش سور سطح الغرف العلوية — GRC", "derived", [["المقطع", "50 × 20 سم (نفس تفصيل C)"], ["الموضع", "قمة السور العلوي +27.25"]],
                             ["استُعمل تفصيل C لأن الواجهات تُظهر كورنيشًا أصغر من كورنيش السطح الرئيسي؛ التفصيل الدقيق غير مذكور"], ["A2600", "A200–A203"]),
        "fence_ramp": T("سياج المنحدر 90 سم", "doc", [["الارتفاع", "90 سم فوق قمة الجدار (+1.40 إلى +2.30)"], ["المادة", "فولاذ مدهون رمادي داكن (كسياج الألعاب)"], ["الموضع", "الجدار الجنوبي المستقيم للمنحدر x=1850..2920"]],
                            ["تقسيم القضبان العمودية (كل 12 سم) وأقطار الأنابيب وعدد الأعمدة افتراض", "السياج يبدأ من نهاية القوس x=2920 حتى x=1850 كما يوحي خط الإشارة في A2301"], ["A2301 «FENCING HIGHT 90cm»"]),
        "site_wall_lamp": T("كشاف جداري خارجي مقاوم للماء 20 واط", "doc", [["القدرة", "20 واط"], ["التركيب", "على السور، ارتفاع 2.30 م (H -230)"], ["الحماية", "مقاوم للماء (WP)"]],
                            ["منسوب +0.20 مرجع الأرض لقياس الارتفاع 2.30 م", "أبعاد الجسم (≈16×18×24 سم) من رمز المخطط"], ["A2301 LIGHT DETAILS"]),
        "site_post_light": T("عمود إنارة حديقة (POST LIGHT)", "derived", [["الرمز", "4 دوائر حول مركز على A2301"], ["الموضع", "الحدائق وممرات منطقة الألعاب"]],
                             ["ارتفاع العمود 3.5 م وشكل الرؤوس الأربعة والقدرة غير مذكورة — المخطط يعطي المسقط فقط (4 دوائر حول مركز)"], ["A2301 LIGHT DETAILS"]),
        "canopy_rib": T("ضلع قوس مظلة المواقف (فولاذ)", "doc", [["الارتفاع الأعلى للحزمة", "T.O.B +3.00"], ["العدد", "ضلع عند كل فاصل مواقف (270 سم)"], ["المقطع", "قوس منحنٍ بفتحة 568 سم"]],
                        ["منحنى القوس وارتفاع قمته (+3.40) وقطر الأنبوب ⌀12 سم قراءات من الرسم لا أرقام مكتوبة", "الصور (7 أغسطس) تؤكد مظلة غشائية بيج على هيكل فولاذي بينما A1700/A201 يذكران برجولة ألمنيوم بتأثير خشب — بانتظار تأكيدك أيّهما المعتمد"], ["A200/A202 المقطع", "A102 المسقط"]),
        "canopy_column": T("عمود مظلة المواقف (أنبوب فولاذ)", "doc", [["الارتفاع", "250 سم"], ["العدد", "عمود عند كل ضلع"]], ["القطر ⌀20 سم تقدير من الرسم", "موضع العمود على القوس (x≈4383 على الكتل الشرقية) مقروء من المقطع"], ["A200/A202"]),
        "canopy_strut": T("ساق مائلة لمظلة المواقف", "doc", [["الربط", "من العمود عند 145 سم إلى القوس"]], ["القطر ⌀8 سم تقدير"], ["A200/A202"]),
        "canopy_membrane": T("قماش مظلة المواقف (غشاء)", "derived", [["اللون", "بيج (من صور الموقع 7 أغسطس)"], ["الشكل", "سطح أسطواني فوق الأضلاع"]],
                             ["المادة وسُمك الغشاء غير محددين في المخططات؛ الصور تُظهر مظلة غشائية بيج بينما A1700/A201 يذكران برجولة ألمنيوم بتأثير خشب — بانتظار تأكيدك أيّهما المعتمد"], ["صور الموقع", "A102"]),
    }

def build(M):
    els = cornices(M) + ramp_fence() + site_lights(M) + parking_canopies(M)
    return {"els": els, "mats": MATS, "types": types()}
